### ISSUE TITLE
Improve description on building a Prologue or Epilogue UI

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#20]
Reminder to Improve description on UI & text placement to the example/template give in https://github.com/NPBruce/valkyrie/issues/1003
And not to forget credits to @EwenDC

**Comment by antontimmermans** [comment]
done in a new chapter in the appendix: Introduction UI - the prologue,
 kindly check it its ok and close this issue

**Comment by EwenDC** [comment]
Hi mate, you've done a good job creating a prologue template that everyone can use, especially without resorting to stitching together images like I did.

However, the main point I was trying to make in that thread was to use "vertical" units for UI elements as well as center anchoring. The problematic thing about "horizontal" units is that's the direction that aspect ratios scale in. While it's generally ok to lose a bit of room horizontally since that's the longer direction, vertically there isn't much room to lose, but that's the direction that will shrink with "horizontal" units turned on. By using "vertical" units you can instead scale horizontally where you've got room to spare.

I would recommend redoing your template with "vertical" units instead, which unfortunately requires repositioning everything. Luckily things like the background work much better for vertical units as you can leave it at x: 0, y:0 with scale 1 and it will fill the screen at all aspect ratio's.

**Comment by antontimmermans** [comment]
@EwenDC Thank you for this clarification, I missed that very relevant point the first time :). I will try and find the correct values with Vertical settings and update the manual.

**Comment by antontimmermans** [comment]
@EwenDC @scrubbless  i updated the chapter using Vertical units. EwenDC was right, vertical alignement does scale better with the different aspects

**Comment by scrubbless** [comment]
Thanks @antontimmermans and @ewendc. Closing this out
